### ISSUE TITLE
Players moving with artificial thrusters break the rendering threshold

### ISSUE THREAD

**Issue by Crcoli7307** [iiPythonx/xenon#3]
If a player is launched, lets say with a trampoline, it will cause the position update to occur meaning afk players on surfaces such as a trampoline will not idle and continue rendering parts.

**Comment by Crcoli7307** [comment]
Perhaps require an input from UIS before checking position to see if new parts need rendered.

**Comment by iiPythonx** [comment]
Solved as of 021dacd
